# Generated by Django 5.1.6 on 2025-02-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_post_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
